### ISSUE TITLE
somthing about replay buffer

### ISSUE THREAD

**Issue by liyuyuc** [msinto93/D4PG#3]
In your code, you use threading.Event() to control the competition between 'Learner' and 'Agent' when 'Learner' wants to delete extra samples from experience buffer and 'Agent' wants to add samples to experience buffer.
But would it be wrong that when several 'agents'  all compete to add sample to experience buffer, but there is no 'lock' to control this competition among threading 'agents'???

**Comment by msinto93** [comment]
I don't think its really necessary to have a lock between the agents themselves. Of course, if you want to be 100% 'thread-safe' then yes you could do this, but any other implementations I've seen of multi-threaded data gathering do not bother with this. The way I see it is that the worst that could happen is that on the rare occasions two or more agents try to add their samples at the same time, one sample may be overwritten. This isn't a significant issue given that we aren't adding to the buffer every step, only at the end of an episode, so the chances of trying to add at the exact same time as another agent are fairly low.

**Comment by liyuyuc** [comment]
> I don't think its really necessary to have a lock between the agents themselves. Of course, if you want to be 100% 'thread-safe' then yes you could do this, but any other implementations I've seen of multi-threaded data gathering do not bother with this. The way I see it is that the worst that could happen is that on the rare occasions two or more agents try to add their samples at the same time, one sample may be overwritten. This isn't a significant issue given that we aren't adding to the buffer every step, only at the end of an episode, so the chances of trying to add at the exact same time as another agent are fairly low.

thanks!
